#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef LAMPSSDK_SWIFT_H
#define LAMPSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LampsSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class LampsSDKConfig;
@class UIViewController;
@class LampsGameCenterConfig;
@class UIView;
/// Lamps SDK 入口。接入方 <code>import LampsSDK</code> 后先 <code>start</code>，再 <code>showGameCenter(from:)</code> 打开游戏中心，<code>showGame(gameId:)</code> 打开具体游戏，或 <code>makeGameCenterView()</code> 嵌入页面。
/// 类名不用 <code>LampsSDK</code>，避免与模块名冲突。
SWIFT_CLASS("_TtC8LampsSDK5Lamps")
@interface Lamps : NSObject
/// 当前 SDK 版本号。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// 启动 SDK。请在打开活动页之前调用，重复调用不会重新初始化广告 SDK。
/// 会校验 <code>appId</code>、读取本地配置缓存并请求远端配置，再按配置初始化已接入的广告 SDK。
/// 配置请求失败时：有磁盘缓存则仍回调成功并继续使用缓存；无缓存则回调失败。
/// 默认正式环境；测试环境请用 <code>LampsDevTools</code> 切换。
/// \param config 初始化配置，<code>appId</code> 必填。SDK 会拷贝一份，之后修改原对象不会生效。
///
/// \param completion 启动完成回调，主线程。
///
+ (void)startWithConfig:(LampsSDKConfig * _Nonnull)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 是否已调用过 <code>start</code>。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isStarted;)
+ (BOOL)isStarted SWIFT_WARN_UNUSED_RESULT;
/// 最近一次 <code>start</code> 使用的配置；尚未启动时为 <code>nil</code>。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsSDKConfig * _Nullable config;)
+ (LampsSDKConfig * _Nullable)config SWIFT_WARN_UNUSED_RESULT;
/// 在宿主导航栈中打开游戏中心。请先 <code>start</code> 成功。
/// 当前页有导航栈则 <code>push</code>，否则全屏 <code>present</code>。关闭由 H5 触发，或调用页内关闭。
/// 若希望独立全屏打开、不进入宿主导航栈，请用 <code>presentGameCenter</code>。
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param config 本次展示配置；不传则用 <code>LampsSDKConfig</code> 中的对应字段。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)showGameCenterFromViewController:(UIViewController * _Nullable)viewController config:(LampsGameCenterConfig * _Nullable)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 全屏打开游戏中心，不进入宿主导航栈。请先 <code>start</code> 成功。
/// SDK 会用自有导航容器 present，系统导航栏默认隐藏。从游戏中心再打开具体游戏时，仍在该容器内跳转。
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param config 本次展示配置；不传则用 <code>LampsSDKConfig</code> 中的对应字段。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)presentGameCenterFromViewController:(UIViewController * _Nullable)viewController config:(LampsGameCenterConfig * _Nullable)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 在宿主导航栈中打开具体游戏页。请先 <code>start</code> 成功。
/// 使用配置下发的 <code>gamePageUrl</code>，将链接中的 <code>__GAMEID__</code> 替换为 <code>gameId</code> 后加载。
/// 当前页有导航栈则 <code>push</code>，否则全屏 <code>present</code>。容器为 <code>LampsGameWebViewController</code>。
/// 若希望独立全屏打开、不进入宿主导航栈，请用 <code>presentGame</code>。
/// \param gameId 游戏 ID，替换 <code>gamePageUrl</code> 中的 <code>__GAMEID__</code>。
///
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)showGameWithGameId:(NSString * _Nonnull)gameId fromViewController:(UIViewController * _Nullable)viewController completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 全屏打开具体游戏页，不进入宿主导航栈。请先 <code>start</code> 成功。
/// 使用配置下发的 <code>gamePageUrl</code>，将链接中的 <code>__GAMEID__</code> 替换为 <code>gameId</code> 后加载。
/// SDK 会用自有导航容器 present，系统导航栏默认隐藏。
/// \param gameId 游戏 ID，替换 <code>gamePageUrl</code> 中的 <code>__GAMEID__</code>。
///
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)presentGameWithGameId:(NSString * _Nonnull)gameId fromViewController:(UIViewController * _Nullable)viewController completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 使用配置下发的 <code>gameCenterPage</code> 创建可内嵌视图。请先 <code>start</code> 成功。
/// 返回的是内部 WebView，类型对外为 <code>UIView</code>。地址不可用时返回 <code>nil</code>。
/// 请由宿主加入自己的视图层级并设置约束。
/// 从该视图内再打开具体游戏时，SDK 会全屏 present，不进入宿主导航栈。
/// \param config 本次展示配置；不传则用 <code>LampsSDKConfig</code> 中的对应字段。
///
+ (UIView * _Nullable)makeGameCenterViewWithConfig:(LampsGameCenterConfig * _Nullable)config SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 日夜间。
typedef SWIFT_ENUM(NSInteger, LampsDayNightMode, open) {
  LampsDayNightModeDay = 0,
  LampsDayNightModeNight = 1,
};

/// 打开或嵌入游戏中心时的展示配置。不传则用 <code>LampsSDKConfig</code> 中的对应字段。
SWIFT_CLASS("_TtC8LampsSDK21LampsGameCenterConfig")
@interface LampsGameCenterConfig : NSObject
/// 日夜间，默认日间。
@property (nonatomic) enum LampsDayNightMode dayNightMode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDayNightMode:(enum LampsDayNightMode)dayNightMode;
@end

@class NSCoder;
@class NSBundle;
/// 全屏活动容器：隐藏系统导航栏，整页交给 H5。
/// 请 <code>push</code> 或 <code>present</code> 本页。关闭由 H5 Bridge <code>close</code> 触发，也可调用 <code>closePage()</code>。
/// 游戏 H5 请使用 <code>LampsGameWebViewController</code>。
SWIFT_CLASS("_TtC8LampsSDK22LampsWebViewController")
@interface LampsWebViewController : UIViewController
/// 当前活动 URL；本地 HTML 模式下为空字符串。
@property (nonatomic, readonly, copy) NSString * _Nonnull urlString;
/// 本地 HTML；通过 URL 打开时为 <code>nil</code>。
@property (nonatomic, readonly, copy) NSString * _Nullable htmlString;
/// 打开远端活动页。
- (nonnull instancetype)initWithURLString:(NSString * _Nonnull)urlString;
/// 加载本地 HTML，建议仅用于调试。
- (nonnull instancetype)initWithHTMLString:(NSString * _Nonnull)htmlString;
- (nonnull instancetype)initWithUrlString:(NSString * _Nonnull)urlString htmlString:(NSString * _Nullable)htmlString OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
/// 关闭当前页：栈内有上级则 <code>pop</code>，自身或所在导航容器为模态根页时才 <code>dismiss</code>。
- (void)closePage;
/// 重新加载当前页：本地 HTML 再注入一次，否则按原 URL 重新请求。
- (void)reloadPage;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// 游戏 H5 容器：在 <code>LampsWebViewController</code> 之上增加悬浮菜单条（更多 + 关闭）。
/// 菜单可拖拽吸边，静止 3s 收成贴边半圆弧。Bridge、加载、导航栏隐藏与 <code>closePage()</code> 行为与父类一致。
SWIFT_CLASS("_TtC8LampsSDK26LampsGameWebViewController")
@interface LampsGameWebViewController : LampsWebViewController
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithUrlString:(NSString * _Nonnull)urlString htmlString:(NSString * _Nullable)htmlString OBJC_DESIGNATED_INITIALIZER;
@end

/// 单次激励候选素材（由 rewardAdSlots 映射，无 getOther）。
/// 仅 Adapter 跨模块 SPI，宿主普通 import 不可见。
SWIFT_CLASS("_TtC8LampsSDK18LampsRewardAdModel")
@interface LampsRewardAdModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 初始化参数。在调用 <code>Lamps.start</code> 之前设置。
SWIFT_CLASS("_TtC8LampsSDK14LampsSDKConfig")
@interface LampsSDKConfig : NSObject <NSCopying>
/// 分配给宿主 App 的应用 ID，必填。
@property (nonatomic, copy) NSString * _Nonnull appId;
/// 日夜间，默认日间。打开游戏中心时未传 <code>LampsGameCenterConfig</code> 则用该值。
@property (nonatomic) enum LampsDayNightMode dayNightMode;
/// 是否打印 <code>[LampsSDK]</code> 调试日志。正式包请保持关闭。
@property (nonatomic) BOOL debugLogEnabled;
/// 是否开启个性化推荐广告，默认开启。
@property (nonatomic) BOOL personalizedRecommendEnabled;
/// 是否开启摇一摇类互动广告，默认开启。
@property (nonatomic) BOOL shakeAdsEnabled;
/// 是否允许广告 SDK 使用定位，默认关闭。
@property (nonatomic) BOOL allowLocation;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// SDK 失败时 <code>NSError.code</code>。
typedef SWIFT_ENUM(NSInteger, LampsSDKErrorCode, open) {
/// 尚未调用 <code>Lamps.start</code>。
  LampsSDKErrorCodeNotStarted = -1001,
/// 初始化参数不合法，例如 <code>appId</code> 为空。
  LampsSDKErrorCodeInvalidConfig = -1002,
/// 配置接口地址无效或 URL 组装失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeConfigURLError = -1003,
/// 配置请求失败，或响应为空 / 格式错误 / 解析失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeConfigFetchError = -1004,
/// 广告 SDK 初始化失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeAdSDKInitializeError = -1005,
/// 激励视频进行中，无法开始新的一次。
  LampsSDKErrorCodeRewardBusy = -1006,
/// 激励视频请求 / 加载失败（含超时、全部渠道失败）。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeRewardLoadError = -1007,
/// 激励视频展示失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeRewardShowError = -1008,
/// 游戏中心地址为空或 URL 不合法。
  LampsSDKErrorCodeGameCenterUnavailable = -1009,
/// 找不到可用于展示的页面。
  LampsSDKErrorCodeNoHostViewController = -1010,
/// 游戏页地址为空或 URL 不合法。
  LampsSDKErrorCodeGamePageUnavailable = -1011,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef LAMPSSDK_SWIFT_H
#define LAMPSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LampsSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class LampsSDKConfig;
@class UIViewController;
@class LampsGameCenterConfig;
@class UIView;
/// Lamps SDK 入口。接入方 <code>import LampsSDK</code> 后先 <code>start</code>，再 <code>showGameCenter(from:)</code> 打开游戏中心，<code>showGame(gameId:)</code> 打开具体游戏，或 <code>makeGameCenterView()</code> 嵌入页面。
/// 类名不用 <code>LampsSDK</code>，避免与模块名冲突。
SWIFT_CLASS("_TtC8LampsSDK5Lamps")
@interface Lamps : NSObject
/// 当前 SDK 版本号。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// 启动 SDK。请在打开活动页之前调用，重复调用不会重新初始化广告 SDK。
/// 会校验 <code>appId</code>、读取本地配置缓存并请求远端配置，再按配置初始化已接入的广告 SDK。
/// 配置请求失败时：有磁盘缓存则仍回调成功并继续使用缓存；无缓存则回调失败。
/// 默认正式环境；测试环境请用 <code>LampsDevTools</code> 切换。
/// \param config 初始化配置，<code>appId</code> 必填。SDK 会拷贝一份，之后修改原对象不会生效。
///
/// \param completion 启动完成回调，主线程。
///
+ (void)startWithConfig:(LampsSDKConfig * _Nonnull)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 是否已调用过 <code>start</code>。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isStarted;)
+ (BOOL)isStarted SWIFT_WARN_UNUSED_RESULT;
/// 最近一次 <code>start</code> 使用的配置；尚未启动时为 <code>nil</code>。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsSDKConfig * _Nullable config;)
+ (LampsSDKConfig * _Nullable)config SWIFT_WARN_UNUSED_RESULT;
/// 在宿主导航栈中打开游戏中心。请先 <code>start</code> 成功。
/// 当前页有导航栈则 <code>push</code>，否则全屏 <code>present</code>。关闭由 H5 触发，或调用页内关闭。
/// 若希望独立全屏打开、不进入宿主导航栈，请用 <code>presentGameCenter</code>。
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param config 本次展示配置；不传则用 <code>LampsSDKConfig</code> 中的对应字段。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)showGameCenterFromViewController:(UIViewController * _Nullable)viewController config:(LampsGameCenterConfig * _Nullable)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 全屏打开游戏中心，不进入宿主导航栈。请先 <code>start</code> 成功。
/// SDK 会用自有导航容器 present，系统导航栏默认隐藏。从游戏中心再打开具体游戏时，仍在该容器内跳转。
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param config 本次展示配置；不传则用 <code>LampsSDKConfig</code> 中的对应字段。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)presentGameCenterFromViewController:(UIViewController * _Nullable)viewController config:(LampsGameCenterConfig * _Nullable)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 在宿主导航栈中打开具体游戏页。请先 <code>start</code> 成功。
/// 使用配置下发的 <code>gamePageUrl</code>，将链接中的 <code>__GAMEID__</code> 替换为 <code>gameId</code> 后加载。
/// 当前页有导航栈则 <code>push</code>，否则全屏 <code>present</code>。容器为 <code>LampsGameWebViewController</code>。
/// 若希望独立全屏打开、不进入宿主导航栈，请用 <code>presentGame</code>。
/// \param gameId 游戏 ID，替换 <code>gamePageUrl</code> 中的 <code>__GAMEID__</code>。
///
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)showGameWithGameId:(NSString * _Nonnull)gameId fromViewController:(UIViewController * _Nullable)viewController completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 全屏打开具体游戏页，不进入宿主导航栈。请先 <code>start</code> 成功。
/// 使用配置下发的 <code>gamePageUrl</code>，将链接中的 <code>__GAMEID__</code> 替换为 <code>gameId</code> 后加载。
/// SDK 会用自有导航容器 present，系统导航栏默认隐藏。
/// \param gameId 游戏 ID，替换 <code>gamePageUrl</code> 中的 <code>__GAMEID__</code>。
///
/// \param viewController 起始页面，可不传；未传时 SDK 取当前最上层页面。
///
/// \param completion 打开结果。失败时 <code>error</code> 的 <code>domain</code> 为 <code>LampsSDKErrorDomain</code>，<code>code</code> 见 <code>LampsSDKErrorCode</code>。
///
+ (void)presentGameWithGameId:(NSString * _Nonnull)gameId fromViewController:(UIViewController * _Nullable)viewController completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 使用配置下发的 <code>gameCenterPage</code> 创建可内嵌视图。请先 <code>start</code> 成功。
/// 返回的是内部 WebView，类型对外为 <code>UIView</code>。地址不可用时返回 <code>nil</code>。
/// 请由宿主加入自己的视图层级并设置约束。
/// 从该视图内再打开具体游戏时，SDK 会全屏 present，不进入宿主导航栈。
/// \param config 本次展示配置；不传则用 <code>LampsSDKConfig</code> 中的对应字段。
///
+ (UIView * _Nullable)makeGameCenterViewWithConfig:(LampsGameCenterConfig * _Nullable)config SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 日夜间。
typedef SWIFT_ENUM(NSInteger, LampsDayNightMode, open) {
  LampsDayNightModeDay = 0,
  LampsDayNightModeNight = 1,
};

/// 打开或嵌入游戏中心时的展示配置。不传则用 <code>LampsSDKConfig</code> 中的对应字段。
SWIFT_CLASS("_TtC8LampsSDK21LampsGameCenterConfig")
@interface LampsGameCenterConfig : NSObject
/// 日夜间，默认日间。
@property (nonatomic) enum LampsDayNightMode dayNightMode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDayNightMode:(enum LampsDayNightMode)dayNightMode;
@end

@class NSCoder;
@class NSBundle;
/// 全屏活动容器：隐藏系统导航栏，整页交给 H5。
/// 请 <code>push</code> 或 <code>present</code> 本页。关闭由 H5 Bridge <code>close</code> 触发，也可调用 <code>closePage()</code>。
/// 游戏 H5 请使用 <code>LampsGameWebViewController</code>。
SWIFT_CLASS("_TtC8LampsSDK22LampsWebViewController")
@interface LampsWebViewController : UIViewController
/// 当前活动 URL；本地 HTML 模式下为空字符串。
@property (nonatomic, readonly, copy) NSString * _Nonnull urlString;
/// 本地 HTML；通过 URL 打开时为 <code>nil</code>。
@property (nonatomic, readonly, copy) NSString * _Nullable htmlString;
/// 打开远端活动页。
- (nonnull instancetype)initWithURLString:(NSString * _Nonnull)urlString;
/// 加载本地 HTML，建议仅用于调试。
- (nonnull instancetype)initWithHTMLString:(NSString * _Nonnull)htmlString;
- (nonnull instancetype)initWithUrlString:(NSString * _Nonnull)urlString htmlString:(NSString * _Nullable)htmlString OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
/// 关闭当前页：栈内有上级则 <code>pop</code>，自身或所在导航容器为模态根页时才 <code>dismiss</code>。
- (void)closePage;
/// 重新加载当前页：本地 HTML 再注入一次，否则按原 URL 重新请求。
- (void)reloadPage;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// 游戏 H5 容器：在 <code>LampsWebViewController</code> 之上增加悬浮菜单条（更多 + 关闭）。
/// 菜单可拖拽吸边，静止 3s 收成贴边半圆弧。Bridge、加载、导航栏隐藏与 <code>closePage()</code> 行为与父类一致。
SWIFT_CLASS("_TtC8LampsSDK26LampsGameWebViewController")
@interface LampsGameWebViewController : LampsWebViewController
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithUrlString:(NSString * _Nonnull)urlString htmlString:(NSString * _Nullable)htmlString OBJC_DESIGNATED_INITIALIZER;
@end

/// 单次激励候选素材（由 rewardAdSlots 映射，无 getOther）。
/// 仅 Adapter 跨模块 SPI，宿主普通 import 不可见。
SWIFT_CLASS("_TtC8LampsSDK18LampsRewardAdModel")
@interface LampsRewardAdModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 初始化参数。在调用 <code>Lamps.start</code> 之前设置。
SWIFT_CLASS("_TtC8LampsSDK14LampsSDKConfig")
@interface LampsSDKConfig : NSObject <NSCopying>
/// 分配给宿主 App 的应用 ID，必填。
@property (nonatomic, copy) NSString * _Nonnull appId;
/// 日夜间，默认日间。打开游戏中心时未传 <code>LampsGameCenterConfig</code> 则用该值。
@property (nonatomic) enum LampsDayNightMode dayNightMode;
/// 是否打印 <code>[LampsSDK]</code> 调试日志。正式包请保持关闭。
@property (nonatomic) BOOL debugLogEnabled;
/// 是否开启个性化推荐广告，默认开启。
@property (nonatomic) BOOL personalizedRecommendEnabled;
/// 是否开启摇一摇类互动广告，默认开启。
@property (nonatomic) BOOL shakeAdsEnabled;
/// 是否允许广告 SDK 使用定位，默认关闭。
@property (nonatomic) BOOL allowLocation;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// SDK 失败时 <code>NSError.code</code>。
typedef SWIFT_ENUM(NSInteger, LampsSDKErrorCode, open) {
/// 尚未调用 <code>Lamps.start</code>。
  LampsSDKErrorCodeNotStarted = -1001,
/// 初始化参数不合法，例如 <code>appId</code> 为空。
  LampsSDKErrorCodeInvalidConfig = -1002,
/// 配置接口地址无效或 URL 组装失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeConfigURLError = -1003,
/// 配置请求失败，或响应为空 / 格式错误 / 解析失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeConfigFetchError = -1004,
/// 广告 SDK 初始化失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeAdSDKInitializeError = -1005,
/// 激励视频进行中，无法开始新的一次。
  LampsSDKErrorCodeRewardBusy = -1006,
/// 激励视频请求 / 加载失败（含超时、全部渠道失败）。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeRewardLoadError = -1007,
/// 激励视频展示失败。具体原因看 <code>localizedDescription</code>。
  LampsSDKErrorCodeRewardShowError = -1008,
/// 游戏中心地址为空或 URL 不合法。
  LampsSDKErrorCodeGameCenterUnavailable = -1009,
/// 找不到可用于展示的页面。
  LampsSDKErrorCodeNoHostViewController = -1010,
/// 游戏页地址为空或 URL 不合法。
  LampsSDKErrorCodeGamePageUnavailable = -1011,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
