#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef LAMPSSDK_SWIFT_H
#define LAMPSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LampsSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class LampsSDKConfig;
@class LampsRemoteConfig;
/// 对外总入口。宿主 <code>import LampsSDK</code> 后调用 <code>Lamps.start(config:completion:)</code>。
/// 类名刻意不用 <code>LampsSDK</code>，避免与模块名同名导致 <code>.swiftinterface</code> 解析冲突。
SWIFT_CLASS("_TtC8LampsSDK5Lamps")
@interface Lamps : NSObject
/// 启动 SDK。
/// 流程：本地校验 → 初始化已注册广告 SDK → 请求 <code>/v1/lamps/config</code> → 回调。
/// 配置接口失败时仍视为启动成功（<code>success=true</code>），可从 <code>remoteConfig</code> 判断是否拉到配置。
+ (void)startWithConfig:(LampsSDKConfig * _Nonnull)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isStarted;)
+ (BOOL)isStarted SWIFT_WARN_UNUSED_RESULT;
/// 当前生效配置；未启动时为 nil。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsSDKConfig * _Nullable config;)
+ (LampsSDKConfig * _Nullable)config SWIFT_WARN_UNUSED_RESULT;
/// 远端配置；未拉取成功时为 nil。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsRemoteConfig * _Nullable remoteConfig;)
+ (LampsRemoteConfig * _Nullable)remoteConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LampsBridge;
@class NSString;
/// 一组业务 Bridge。导航、激励视频等各自实现，由 <code>LampsBridge</code> 按 method 分发。
SWIFT_PROTOCOL("_TtP8LampsSDK18LampsBridgeHandler_")
@protocol LampsBridgeHandler
@property (nonatomic, strong) LampsBridge * _Nullable bridge;
/// 该 Handler 负责的方法名。
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull supportedMethods;
/// 处理 H5 调用。success / error 是本次调用的回调，不需要注册。
- (void)handleWithMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
@end

/// 基础能力：ping。
SWIFT_CLASS("_TtC8LampsSDK22LampsBaseBridgeHandler")
@interface LampsBaseBridgeHandler : NSObject <LampsBridgeHandler>
@property (nonatomic, weak) LampsBridge * _Nullable bridge;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull supportedMethods;
- (void)handleWithMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LampsWebView;
@class WKUserContentController;
@class WKScriptMessage;
/// 挂在 <code>LampsWebView</code> 上的 Bridge。
/// <ul>
///   <li>
///     H5 → Native：按 method 分发给 Handler
///   </li>
///   <li>
///     Native → H5：<code>send(method:data:success:error:)</code> 主动调用
///   </li>
/// </ul>
SWIFT_CLASS("_TtC8LampsSDK11LampsBridge")
@interface LampsBridge : NSObject <WKScriptMessageHandler>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull messageName;)
+ (NSString * _Nonnull)messageName SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) LampsWebView * _Nullable webView;
@property (nonatomic, readonly, copy) NSArray<id <LampsBridgeHandler>> * _Nonnull handlers;
- (nonnull instancetype)initWithWebView:(LampsWebView * _Nonnull)webView OBJC_DESIGNATED_INITIALIZER;
/// 添加一组业务 Handler。
- (void)addHandler:(id <LampsBridgeHandler> _Nonnull)handler;
/// Native 主动调用 H5。H5 需实现 <code>_handle_(method, data, successcb, errorcb)</code>。
- (void)sendMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
/// 解析 JSON 字符串并分发。
- (void)flushMessageQueue:(NSString * _Nonnull)jsStr;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8LampsSDK17LampsMonitorLinks")
@interface LampsMonitorLinks : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull rm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull pm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull cm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull dm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull wm;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 导航相关：close。
SWIFT_CLASS("_TtC8LampsSDK28LampsNavigationBridgeHandler")
@interface LampsNavigationBridgeHandler : NSObject <LampsBridgeHandler>
@property (nonatomic, weak) LampsBridge * _Nullable bridge;
@property (nonatomic, copy) void (^ _Nullable closeHandler)(void);
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull supportedMethods;
- (void)handleWithMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LampsRewardAdSlot;
/// <code>/v1/lamps/config</code> 返回的 data。
SWIFT_CLASS("_TtC8LampsSDK17LampsRemoteConfig")
@interface LampsRemoteConfig : NSObject
@property (nonatomic, copy) NSArray<LampsRewardAdSlot *> * _Nonnull rewardAdSlots;
@property (nonatomic, copy) NSString * _Nonnull token;
@property (nonatomic, copy) NSString * _Nonnull clientIp;
@property (nonatomic, strong) LampsMonitorLinks * _Nonnull monitorLinks;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, LampsReportType, open) {
  LampsReportTypeRm = 0,
  LampsReportTypeWm = 1,
  LampsReportTypeCm = 2,
  LampsReportTypePm = 3,
  LampsReportTypeRem = 4,
};

/// 监测上报入口：宏替换后 GET。
/// 支持 RM / WM / CM / PM / REM，不区分 SDK 与 API。
SWIFT_CLASS("_TtC8LampsSDK13LampsReporter")
@interface LampsReporter : NSObject
/// 统一上报。
+ (void)reportWithType:(enum LampsReportType)type urls:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportRMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportWMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportCMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportPMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportREMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@class LampsRewardCallback;
enum LampsRewardChannel : NSInteger;
/// 对外便捷入口。
SWIFT_CLASS("_TtC8LampsSDK13LampsRewardAd")
@interface LampsRewardAd : NSObject
+ (void)showFromViewController:(UIViewController * _Nonnull)viewController completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
+ (void)showFromViewController:(UIViewController * _Nonnull)viewController handler:(void (^ _Nullable)(LampsRewardCallback * _Nonnull))handler completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
+ (BOOL)isAdapterAvailable:(enum LampsRewardChannel)channel SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 单次激励候选素材（由 rewardAdSlots 映射，无 getOther）。
SWIFT_CLASS("_TtC8LampsSDK18LampsRewardAdModel")
@interface LampsRewardAdModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8LampsSDK17LampsRewardAdSlot")
@interface LampsRewardAdSlot : NSObject
/// 代码位 ID
@property (nonatomic, copy) NSString * _Nonnull slotId;
/// 类型：BD、PD
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull channelName;
@property (nonatomic, copy) NSString * _Nonnull channelId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LampsRewardCallbackName : NSInteger;
SWIFT_CLASS("_TtC8LampsSDK19LampsRewardCallback")
@interface LampsRewardCallback : NSObject
@property (nonatomic) enum LampsRewardCallbackName name;
@property (nonatomic) BOOL status;
@property (nonatomic) BOOL rewardStatus;
@property (nonatomic) NSInteger errCode;
@property (nonatomic, copy) NSString * _Nullable errMessage;
@property (nonatomic, copy) NSString * _Nonnull channelName;
@property (nonatomic, copy) NSString * _Nonnull slotId;
@property (nonatomic) CGFloat price;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, LampsRewardCallbackName, open) {
  LampsRewardCallbackNameBusy = 0,
  LampsRewardCallbackNameReqError = 1,
  LampsRewardCallbackNameLoadSuccess = 2,
  LampsRewardCallbackNameLoadError = 3,
  LampsRewardCallbackNameShowSuccess = 4,
  LampsRewardCallbackNameShowError = 5,
  LampsRewardCallbackNameRewardArrived = 6,
  LampsRewardCallbackNameClose = 7,
};

/// 激励渠道。用 config <code>channelId</code> 判断（兼容 HCAD dsp：2/327=CSJ，348/349=GDT，417=Noah）。
typedef SWIFT_ENUM(NSInteger, LampsRewardChannel, open) {
  LampsRewardChannelCsj = 1,
  LampsRewardChannelGdt = 2,
  LampsRewardChannelNoah = 3,
};

/// 激励视频编排器（对齐 HCADCommonRewardVideoManager）。
/// 入参使用 config.rewardAdSlots；并行请求已注册 Adapter，竞价后展示赢家。
SWIFT_CLASS("_TtC8LampsSDK23LampsRewardVideoManager")
@interface LampsRewardVideoManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsRewardVideoManager * _Nonnull shared;)
+ (LampsRewardVideoManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isActive;
/// 开始激励流程；生命周期事件通过 handler 回调。
- (void)startFromViewController:(UIViewController * _Nonnull)viewController handler:(void (^ _Nullable)(LampsRewardCallback * _Nonnull))handler;
/// 开始激励；<code>completion</code> 在 close / 失败结束时回调是否发奖。
- (void)startFromViewController:(UIViewController * _Nonnull)viewController handler:(void (^ _Nullable)(LampsRewardCallback * _Nonnull))handler completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LampsSDKEnvironment : NSInteger;
/// SDK 初始化配置。
SWIFT_CLASS("_TtC8LampsSDK14LampsSDKConfig")
@interface LampsSDKConfig : NSObject <NSCopying>
/// 宿主分配的应用标识，初始化时必填。
@property (nonatomic, copy) NSString * _Nonnull appId;
/// 是否打印 SDK 调试日志，默认 false。
@property (nonatomic) BOOL debugLogEnabled;
/// REM 签名密钥。为空时回退使用配置接口返回的 <code>token</code>。
@property (nonatomic, copy) NSString * _Nonnull rewardSignKey;
/// 配置接口环境，默认正式环境。
@property (nonatomic) enum LampsSDKEnvironment environment;
/// 穿山甲 AppId；非空且集成 CSJ Subspec 时会在 start 中初始化。
@property (nonatomic, copy) NSString * _Nonnull csjAppId;
/// 优量汇 AppId；非空且集成 GDT Subspec 时会在 start 中初始化。
@property (nonatomic, copy) NSString * _Nonnull gdtAppId;
/// 汇川 AppKey；非空且集成 Noah Subspec 时会在 start 中初始化。
@property (nonatomic, copy) NSString * _Nonnull noahAppKey;
/// 激励默认超时（毫秒）。
@property (nonatomic) NSInteger rewardTimeoutMs;
/// 激励服务端校验 userId。
@property (nonatomic, copy) NSString * _Nonnull rewardUserId;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 配置接口环境。
typedef SWIFT_ENUM(NSInteger, LampsSDKEnvironment, open) {
  LampsSDKEnvironmentPrd = 0,
  LampsSDKEnvironmentDev = 1,
};

typedef SWIFT_ENUM(NSInteger, LampsSDKErrorCode, open) {
  LampsSDKErrorCodeNotImplemented = -1001,
  LampsSDKErrorCodeNotStarted = -1002,
  LampsSDKErrorCodeInvalidConfig = -1003,
  LampsSDKErrorCodeInvalidURL = -1004,
  LampsSDKErrorCodeNetwork = -1005,
  LampsSDKErrorCodeApi = -1006,
};

@class WKWebViewConfiguration;
@class NSCoder;
@class NSURL;
/// 可独立使用的 WKWebView 子类。页面加载与 Bridge 都挂在这个 View 上。
SWIFT_CLASS("_TtC8LampsSDK12LampsWebView")
@interface LampsWebView : WKWebView
@property (nonatomic, readonly, strong) LampsBridge * _Null_unspecified bridge;
/// H5 调用 <code>close</code> 时触发。
@property (nonatomic, copy) void (^ _Nullable closeHandler)(void);
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// 按字符串加载页面。URL 不合法时返回 false。
- (BOOL)loadURLString:(NSString * _Nonnull)urlString;
+ (NSURL * _Nullable)makeURLFrom:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
+ (WKWebViewConfiguration * _Nonnull)makeConfiguration SWIFT_WARN_UNUSED_RESULT;
@end

@class WKNavigationAction;
@class WKWindowFeatures;
@interface LampsWebView (SWIFT_EXTENSION(LampsSDK)) <WKUIDelegate>
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
@end

@class NSBundle;
/// 全屏 Web 页面容器。真正的加载与 Bridge 都在 <code>LampsWebView</code> 上。
SWIFT_CLASS("_TtC8LampsSDK22LampsWebViewController")
@interface LampsWebViewController : UIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull urlString;
@property (nonatomic, readonly, copy) NSString * _Nullable htmlString;
@property (nonatomic, readonly, strong) LampsWebView * _Nonnull webView;
- (nonnull instancetype)initWithURLString:(NSString * _Nonnull)urlString;
- (nonnull instancetype)initWithHTMLString:(NSString * _Nonnull)htmlString;
- (nonnull instancetype)initWithUrlString:(NSString * _Nonnull)urlString htmlString:(NSString * _Nullable)htmlString OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef LAMPSSDK_SWIFT_H
#define LAMPSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LampsSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class LampsSDKConfig;
@class LampsRemoteConfig;
/// 对外总入口。宿主 <code>import LampsSDK</code> 后调用 <code>Lamps.start(config:completion:)</code>。
/// 类名刻意不用 <code>LampsSDK</code>，避免与模块名同名导致 <code>.swiftinterface</code> 解析冲突。
SWIFT_CLASS("_TtC8LampsSDK5Lamps")
@interface Lamps : NSObject
/// 启动 SDK。
/// 流程：本地校验 → 初始化已注册广告 SDK → 请求 <code>/v1/lamps/config</code> → 回调。
/// 配置接口失败时仍视为启动成功（<code>success=true</code>），可从 <code>remoteConfig</code> 判断是否拉到配置。
+ (void)startWithConfig:(LampsSDKConfig * _Nonnull)config completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isStarted;)
+ (BOOL)isStarted SWIFT_WARN_UNUSED_RESULT;
/// 当前生效配置；未启动时为 nil。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsSDKConfig * _Nullable config;)
+ (LampsSDKConfig * _Nullable)config SWIFT_WARN_UNUSED_RESULT;
/// 远端配置；未拉取成功时为 nil。
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsRemoteConfig * _Nullable remoteConfig;)
+ (LampsRemoteConfig * _Nullable)remoteConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LampsBridge;
@class NSString;
/// 一组业务 Bridge。导航、激励视频等各自实现，由 <code>LampsBridge</code> 按 method 分发。
SWIFT_PROTOCOL("_TtP8LampsSDK18LampsBridgeHandler_")
@protocol LampsBridgeHandler
@property (nonatomic, strong) LampsBridge * _Nullable bridge;
/// 该 Handler 负责的方法名。
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull supportedMethods;
/// 处理 H5 调用。success / error 是本次调用的回调，不需要注册。
- (void)handleWithMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
@end

/// 基础能力：ping。
SWIFT_CLASS("_TtC8LampsSDK22LampsBaseBridgeHandler")
@interface LampsBaseBridgeHandler : NSObject <LampsBridgeHandler>
@property (nonatomic, weak) LampsBridge * _Nullable bridge;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull supportedMethods;
- (void)handleWithMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LampsWebView;
@class WKUserContentController;
@class WKScriptMessage;
/// 挂在 <code>LampsWebView</code> 上的 Bridge。
/// <ul>
///   <li>
///     H5 → Native：按 method 分发给 Handler
///   </li>
///   <li>
///     Native → H5：<code>send(method:data:success:error:)</code> 主动调用
///   </li>
/// </ul>
SWIFT_CLASS("_TtC8LampsSDK11LampsBridge")
@interface LampsBridge : NSObject <WKScriptMessageHandler>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull messageName;)
+ (NSString * _Nonnull)messageName SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) LampsWebView * _Nullable webView;
@property (nonatomic, readonly, copy) NSArray<id <LampsBridgeHandler>> * _Nonnull handlers;
- (nonnull instancetype)initWithWebView:(LampsWebView * _Nonnull)webView OBJC_DESIGNATED_INITIALIZER;
/// 添加一组业务 Handler。
- (void)addHandler:(id <LampsBridgeHandler> _Nonnull)handler;
/// Native 主动调用 H5。H5 需实现 <code>_handle_(method, data, successcb, errorcb)</code>。
- (void)sendMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
/// 解析 JSON 字符串并分发。
- (void)flushMessageQueue:(NSString * _Nonnull)jsStr;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8LampsSDK17LampsMonitorLinks")
@interface LampsMonitorLinks : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull rm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull pm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull cm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull dm;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull wm;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 导航相关：close。
SWIFT_CLASS("_TtC8LampsSDK28LampsNavigationBridgeHandler")
@interface LampsNavigationBridgeHandler : NSObject <LampsBridgeHandler>
@property (nonatomic, weak) LampsBridge * _Nullable bridge;
@property (nonatomic, copy) void (^ _Nullable closeHandler)(void);
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull supportedMethods;
- (void)handleWithMethod:(NSString * _Nonnull)method data:(NSDictionary * _Nonnull)data success:(void (^ _Nullable)(NSDictionary * _Nonnull))success error:(void (^ _Nullable)(NSDictionary * _Nonnull))error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LampsRewardAdSlot;
/// <code>/v1/lamps/config</code> 返回的 data。
SWIFT_CLASS("_TtC8LampsSDK17LampsRemoteConfig")
@interface LampsRemoteConfig : NSObject
@property (nonatomic, copy) NSArray<LampsRewardAdSlot *> * _Nonnull rewardAdSlots;
@property (nonatomic, copy) NSString * _Nonnull token;
@property (nonatomic, copy) NSString * _Nonnull clientIp;
@property (nonatomic, strong) LampsMonitorLinks * _Nonnull monitorLinks;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, LampsReportType, open) {
  LampsReportTypeRm = 0,
  LampsReportTypeWm = 1,
  LampsReportTypeCm = 2,
  LampsReportTypePm = 3,
  LampsReportTypeRem = 4,
};

/// 监测上报入口：宏替换后 GET。
/// 支持 RM / WM / CM / PM / REM，不区分 SDK 与 API。
SWIFT_CLASS("_TtC8LampsSDK13LampsReporter")
@interface LampsReporter : NSObject
/// 统一上报。
+ (void)reportWithType:(enum LampsReportType)type urls:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportRMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportWMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportCMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportPMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
+ (void)reportREMWithURLs:(NSArray<NSString *> * _Nonnull)urls adInfo:(NSDictionary * _Nullable)adInfo extra:(NSDictionary * _Nullable)extra;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@class LampsRewardCallback;
enum LampsRewardChannel : NSInteger;
/// 对外便捷入口。
SWIFT_CLASS("_TtC8LampsSDK13LampsRewardAd")
@interface LampsRewardAd : NSObject
+ (void)showFromViewController:(UIViewController * _Nonnull)viewController completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
+ (void)showFromViewController:(UIViewController * _Nonnull)viewController handler:(void (^ _Nullable)(LampsRewardCallback * _Nonnull))handler completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
+ (BOOL)isAdapterAvailable:(enum LampsRewardChannel)channel SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 单次激励候选素材（由 rewardAdSlots 映射，无 getOther）。
SWIFT_CLASS("_TtC8LampsSDK18LampsRewardAdModel")
@interface LampsRewardAdModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8LampsSDK17LampsRewardAdSlot")
@interface LampsRewardAdSlot : NSObject
/// 代码位 ID
@property (nonatomic, copy) NSString * _Nonnull slotId;
/// 类型：BD、PD
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull channelName;
@property (nonatomic, copy) NSString * _Nonnull channelId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LampsRewardCallbackName : NSInteger;
SWIFT_CLASS("_TtC8LampsSDK19LampsRewardCallback")
@interface LampsRewardCallback : NSObject
@property (nonatomic) enum LampsRewardCallbackName name;
@property (nonatomic) BOOL status;
@property (nonatomic) BOOL rewardStatus;
@property (nonatomic) NSInteger errCode;
@property (nonatomic, copy) NSString * _Nullable errMessage;
@property (nonatomic, copy) NSString * _Nonnull channelName;
@property (nonatomic, copy) NSString * _Nonnull slotId;
@property (nonatomic) CGFloat price;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, LampsRewardCallbackName, open) {
  LampsRewardCallbackNameBusy = 0,
  LampsRewardCallbackNameReqError = 1,
  LampsRewardCallbackNameLoadSuccess = 2,
  LampsRewardCallbackNameLoadError = 3,
  LampsRewardCallbackNameShowSuccess = 4,
  LampsRewardCallbackNameShowError = 5,
  LampsRewardCallbackNameRewardArrived = 6,
  LampsRewardCallbackNameClose = 7,
};

/// 激励渠道。用 config <code>channelId</code> 判断（兼容 HCAD dsp：2/327=CSJ，348/349=GDT，417=Noah）。
typedef SWIFT_ENUM(NSInteger, LampsRewardChannel, open) {
  LampsRewardChannelCsj = 1,
  LampsRewardChannelGdt = 2,
  LampsRewardChannelNoah = 3,
};

/// 激励视频编排器（对齐 HCADCommonRewardVideoManager）。
/// 入参使用 config.rewardAdSlots；并行请求已注册 Adapter，竞价后展示赢家。
SWIFT_CLASS("_TtC8LampsSDK23LampsRewardVideoManager")
@interface LampsRewardVideoManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LampsRewardVideoManager * _Nonnull shared;)
+ (LampsRewardVideoManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isActive;
/// 开始激励流程；生命周期事件通过 handler 回调。
- (void)startFromViewController:(UIViewController * _Nonnull)viewController handler:(void (^ _Nullable)(LampsRewardCallback * _Nonnull))handler;
/// 开始激励；<code>completion</code> 在 close / 失败结束时回调是否发奖。
- (void)startFromViewController:(UIViewController * _Nonnull)viewController handler:(void (^ _Nullable)(LampsRewardCallback * _Nonnull))handler completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LampsSDKEnvironment : NSInteger;
/// SDK 初始化配置。
SWIFT_CLASS("_TtC8LampsSDK14LampsSDKConfig")
@interface LampsSDKConfig : NSObject <NSCopying>
/// 宿主分配的应用标识，初始化时必填。
@property (nonatomic, copy) NSString * _Nonnull appId;
/// 是否打印 SDK 调试日志，默认 false。
@property (nonatomic) BOOL debugLogEnabled;
/// REM 签名密钥。为空时回退使用配置接口返回的 <code>token</code>。
@property (nonatomic, copy) NSString * _Nonnull rewardSignKey;
/// 配置接口环境，默认正式环境。
@property (nonatomic) enum LampsSDKEnvironment environment;
/// 穿山甲 AppId；非空且集成 CSJ Subspec 时会在 start 中初始化。
@property (nonatomic, copy) NSString * _Nonnull csjAppId;
/// 优量汇 AppId；非空且集成 GDT Subspec 时会在 start 中初始化。
@property (nonatomic, copy) NSString * _Nonnull gdtAppId;
/// 汇川 AppKey；非空且集成 Noah Subspec 时会在 start 中初始化。
@property (nonatomic, copy) NSString * _Nonnull noahAppKey;
/// 激励默认超时（毫秒）。
@property (nonatomic) NSInteger rewardTimeoutMs;
/// 激励服务端校验 userId。
@property (nonatomic, copy) NSString * _Nonnull rewardUserId;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 配置接口环境。
typedef SWIFT_ENUM(NSInteger, LampsSDKEnvironment, open) {
  LampsSDKEnvironmentPrd = 0,
  LampsSDKEnvironmentDev = 1,
};

typedef SWIFT_ENUM(NSInteger, LampsSDKErrorCode, open) {
  LampsSDKErrorCodeNotImplemented = -1001,
  LampsSDKErrorCodeNotStarted = -1002,
  LampsSDKErrorCodeInvalidConfig = -1003,
  LampsSDKErrorCodeInvalidURL = -1004,
  LampsSDKErrorCodeNetwork = -1005,
  LampsSDKErrorCodeApi = -1006,
};

@class WKWebViewConfiguration;
@class NSCoder;
@class NSURL;
/// 可独立使用的 WKWebView 子类。页面加载与 Bridge 都挂在这个 View 上。
SWIFT_CLASS("_TtC8LampsSDK12LampsWebView")
@interface LampsWebView : WKWebView
@property (nonatomic, readonly, strong) LampsBridge * _Null_unspecified bridge;
/// H5 调用 <code>close</code> 时触发。
@property (nonatomic, copy) void (^ _Nullable closeHandler)(void);
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// 按字符串加载页面。URL 不合法时返回 false。
- (BOOL)loadURLString:(NSString * _Nonnull)urlString;
+ (NSURL * _Nullable)makeURLFrom:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
+ (WKWebViewConfiguration * _Nonnull)makeConfiguration SWIFT_WARN_UNUSED_RESULT;
@end

@class WKNavigationAction;
@class WKWindowFeatures;
@interface LampsWebView (SWIFT_EXTENSION(LampsSDK)) <WKUIDelegate>
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
@end

@class NSBundle;
/// 全屏 Web 页面容器。真正的加载与 Bridge 都在 <code>LampsWebView</code> 上。
SWIFT_CLASS("_TtC8LampsSDK22LampsWebViewController")
@interface LampsWebViewController : UIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull urlString;
@property (nonatomic, readonly, copy) NSString * _Nullable htmlString;
@property (nonatomic, readonly, strong) LampsWebView * _Nonnull webView;
- (nonnull instancetype)initWithURLString:(NSString * _Nonnull)urlString;
- (nonnull instancetype)initWithHTMLString:(NSString * _Nonnull)htmlString;
- (nonnull instancetype)initWithUrlString:(NSString * _Nonnull)urlString htmlString:(NSString * _Nullable)htmlString OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
